// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Infrastructure.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(TransactionContext))]
    partial class TransactionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api.Models.EntityModel.TransactionInstallmentModels.TransactionInstallment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<decimal?>("AnticipatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpectedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ParcelNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionNSU")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("TransactionNSU");

                    b.ToTable("TransactionInstallments");
                });

            modelBuilder.Entity("api.Models.EntityModel.Transactions.Transaction", b =>
                {
                    b.Property<long>("NSU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NSU"), 1L, 1);

                    b.Property<string>("AcquirerConfirmation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AcquirerConfirmation");

                    b.Property<bool>("Anticipated")
                        .HasColumnType("bit")
                        .HasColumnName("Anticipated");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ApprovalDate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DisapprovalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DisapprovalDate");

                    b.Property<decimal>("FixedRateCharged")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("FixedRateCharged");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("GrossAmount");

                    b.Property<int>("InstallmentsNumber")
                        .HasColumnType("int")
                        .HasColumnName("InstallmentsNumber");

                    b.Property<int>("LastCardDigits")
                        .HasColumnType("int")
                        .HasColumnName("LastCardDigits");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("NetAmount");

                    b.HasKey("NSU");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("api.Models.EntityModel.TransactionInstallmentModels.TransactionInstallment", b =>
                {
                    b.HasOne("api.Models.EntityModel.Transactions.Transaction", "Transaction")
                        .WithMany("TransactionInstallments")
                        .HasForeignKey("TransactionNSU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("api.Models.EntityModel.Transactions.Transaction", b =>
                {
                    b.Navigation("TransactionInstallments");
                });
#pragma warning restore 612, 618
        }
    }
}
